ros2 service call /add_pose_to_path position_setpoint_interfaces/srv/AddPoseToPath "{x: 0.0,  y: 0.0,  z: 0.0}"
ros2 service call /add_pose_to_path position_setpoint_interfaces/srv/AddPoseToPath "{x: 0.0,  y: -1.0,  z: 0.0}"
ros2 service call /add_pose_to_path position_setpoint_interfaces/srv/AddPoseToPath "{x: 3.0,  y: -1.0,  z: 0.0}"
ros2 service call /add_pose_to_path position_setpoint_interfaces/srv/AddPoseToPath "{x: 3.0,  y: 1.0,  z: 0.0}"
ros2 service call /add_pose_to_path position_setpoint_interfaces/srv/AddPoseToPath "{x: 0.0,  y: 1.0,  z: 0.0}"
ros2 service call /add_pose_to_path position_setpoint_interfaces/srv/AddPoseToPath "{x: 0.0,  y: 0.0,  z: 0.0}"
